# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc283e1d85975626aa937b5b9951eda54f14c289b53311e42a6374263a3cb392cbca5d8e93a7a67ec7dc054a1bda7ffcfafb9954683c776ed80e11fbdceac5b7

test:
  secret_key_base: 320d4516a80add7e635de551e3e6bd14ab6409c93dbe309ad74940bfa5e66d6accddaa2a88a5dd1e001206130f27333cfdf161b057c3242650d725e8bd68469d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["yw5BueizFQMwPpgAFcaeCg"] %>
  yt_key: <%= ENV['nA5IWvETkIaSYQeiuFGGCuxRb1QZXM8KiDTqkhzHeVsxzrGctSdddiQWqE7D01RL'] %>
